[package]
name = "trading-bot"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linera-sdk.workspace = true
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
